### ISSUE TITLE
Home - Problema ao exibir o ANO de cada subsite na listagem

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/central-diadograffiti-theme#6]

**Comment by matheusgimenez** [comment]
É por que estamos usando subdominio. No codigo está sendo puxado o ano via "pasta".

Eu sugiro aqui criarmos uma opção no tema de cada site via kirki para o ano. Ai pegamos essa opção e exibimos na listagem.

**Comment by everaldomatias** [comment]
@matheusgimenez Manda bala...
